# Generated by Django 5.2.1 on 2025-05-27 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='media',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['-id'], 'verbose_name': 'Аудио', 'verbose_name_plural': 'Аудиофайлы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_at'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='audio',
        ),
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', help_text='Уровень сложности урока', max_length=50, null=True, verbose_name='Уровень сложности'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='language',
            field=models.CharField(help_text='например, английский или испанский', max_length=50, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Аудиофайл'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='LessonScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Порядок сцены в уроке', verbose_name='Порядок сцены')),
                ('title', models.CharField(max_length=255, verbose_name='Загаловок сцены')),
                ('content', models.TextField(verbose_name='Контент сцены')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Сцена урока',
                'verbose_name_plural': 'Сцены урока',
                'ordering': ['lesson', 'order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lessons.lessonscene', verbose_name='Сцена')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='lessons.lessonscene', verbose_name='Сцена'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видеофайл')),
                ('scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lessons.lessonscene', verbose_name='Сцена')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеофайлы',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='основное название урока', max_length=255, null=True, verbose_name='название урока'),
        ),
    ]
